version: "3"
name: cloud-board

services:
  api:
    container_name: cloud-board-api
    build:
      context: .
      target: development
    volumes:
      - .:/home/app
    ports:
      - 3333:3333

  www:
    container_name: cloud-board-www
    build:
      context: ../Cloud-Board
    volumes:
      - ../Cloud-Board:/home/app
    ports:
      - 3000:3000
    depends_on:
      - api
